server:
  port: 9001
  
spring:
  zipkin:
    base-url: http://localhost:9411
  application: 
    name: masterdata-service
  datasource: 
    url: jdbc:mysql://localhost:3306/olx-masterdata
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
#    hostname: localhost
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor-app
      
  endpoint:
    shutdown: 
      enabled: true