server:
  port: 9001
  
spring:
  zipkin:
    base-url: http://localhost:9411
  application: 
    name: masterdata-service

  config:
    import: configserver:http://localhost:8888    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
#    hostname: localhost
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor-app
      
  endpoint:
    shutdown: 
      enabled: true